### ISSUE TITLE
Why is there #ifdef DOXYGEN in kalman_example.c?

### ISSUE THREAD

**Issue by jose7165** [sunsided/kalman-clib#2]
Hi, firstly great resource, thanks!

I was wondering why does the kalman_example.c have `#ifdef DOXYGEN`?

This means that without DOXYGEN configured, functions such as `test_kalman_1() `or `test_kalman_2()` will be unavailable. Can we safely remove this ifdef?

**Comment by sunsided** [comment]
Thanks for saying so! 

The main purpose (probably) was to not needlessly compile them for regular use, but - yes, it would seem that you can safely remove it. 🙂

**Comment by jose7165** [comment]
ok great thanks for the clarification!
